import { Poppins, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify";

const poppins= Poppins({
  subsets: ["latin"],
  weight: ["400","500","700","800"],
  variable: "--font-poppins",
})

const roboto= Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${roboto.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar></Navbar>
        <main>
          {children}
          <ToastContainer />
        </main>
        <Footer></Footer>
      </body>
    </html>
  );
}
